### ISSUE TITLE
Segmentation fault on MacOS 13.3.1 M2

### ISSUE THREAD

**Issue by chipotlau** [tschuelia/PyPythia#10]
Hi, 

I used pip to install PyPythia v 1.0.1 on my M2 Mac and am running it using RAxML-NG v 1.1

```
PyPythia version 1.0.1 released by The Exelixis Lab
Developed by: Julia Haag
Latest version: https://github.com/tschuelia/PyPythia
Questions/problems/suggestions? Please open an issue on GitHub.
```

I am able to run pythia -h successfully, but when I try to run the following, I received a segmentation fault error:

```
pythia --msa ./test.fa --raxmlng /Users/emilylau/anaconda3/bin/raxml

[00:00:00] Starting prediction.
[00:00:00] Loading predictor /Users/emilylau/anaconda3/lib/python3.10/site-packages/pypythia/predictors/latest.pckl
zsh: segmentation fault  pythia --msa ./test.fa --raxmlng /Users/emilylau/anaconda3/bin/raxml
```

Do you have any suggestions for resolving this?

Thanks!
Emily

**Comment by tschuelia** [comment]
Hi Emily! 

Thanks for trying out Pythia and thanks for raising the issue!

Unfortunately based on the log file it's hard to see what is going on and whether this is an error in Pythia or RAxML-NG or some other package. Could you please run the following commands (with the respective conda environment activated) and send me the `environment.yaml` and `requirements.txt` files so I can replicate your setup to debug the issue
```
conda env export > environment.yaml
pip freeze > requirements.txt
```
And if possible, could you also send me the `test.fa` MSA? If you don't want to share it here you can also send it via Email.

Thanks,
Julia
