### ISSUE TITLE
Add an output file

### ISSUE THREAD

**Issue by BenoitMorel** [tschuelia/PyPythia#4]
Hi Julia,

I am writing a pipeline that extracts the difficulty score from the logs. But if you change the logs, it will break my pipeline :D
Could you maybe add an option to set an output file that would just contain the score? 
(Any other solution that would be guaranteed to stay stable over time would also work for me)

Thanks!
Benoit

**Comment by tschuelia** [comment]
Hi Benoit,

the output file is a great idea, I just added it as `-o` or `--output` option (also you can now set the precision, if 2 decimals are not sufficient :-)). 
The alternative option would be to run a python code snippet to get the difficulty, but if you are using a file-based pipeline, I think the output file option is better.
I hope this helps and let me know if the output flag does not work as expected.

**Comment by BenoitMorel** [comment]
Thanks a lot, that's exactly what I needed!
