### ISSUE TITLE
Option to clean up the temporary files

### ISSUE THREAD

**Issue by BenoitMorel** [tschuelia/PyPythia#5]
Hi again ;-)
I have run PyThia on several large datasets (with many alignments), and ended up filling my disc with temporary files. 
Since the user is not really aware of those files, maybe PyThia could remove them, either optionally or by default?

**Comment by tschuelia** [comment]
Hi :D 
that is a bit odd, I'm using the python `tempfile` module, which (according to the documentation) does the cleanup. What kind of temporary files are still present? The RAxML-NG files or temporary MSAs?

**Comment by tschuelia** [comment]
`tempfile` should do the clean up immediately when the context ends
turns out I made a mistake, but it should be fixed now ;-)

**Comment by BenoitMorel** [comment]
Yes, it's fixed. Thanks for fixing all the issues to quickly :-)
