### ISSUE TITLE
Error with a protein alignment

### ISSUE THREAD

**Issue by BenoitMorel** [tschuelia/PyPythia#6]
Hi Julia,

PyThia fails to analyze the following MSA:
[fungi_aa.msa.txt](https://github.com/tschuelia/PyPythia/files/9040003/fungi_aa.msa.txt)

It is a protein alignment, but it tries to run raxml-ng with GTR+G. (I am using raxml-ng at the master branch)
That's the only alignment that fails out of 1330.

Benoit

**Comment by tschuelia** [comment]
Yep there was a bug in the type detection for fasta files, I just pushed a fix and it should work now :-)

**Comment by BenoitMorel** [comment]
Great, it works, thanks :-)
