### ISSUE TITLE
Installation doesn't work on MacOS 12.6.2

### ISSUE THREAD

**Issue by willbour** [tschuelia/PyPythia#8]
Cannot install on Mac OS 12.6.2
"note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lightgbm

note: This is an issue with the package mentioned above, not pip" 
Even after installing wheel Lighgbm will not install I have tried Brew pip Anaconda etc. without success. Further the prediction_no_install.py script seems to have a syntax error in line 8 so I can't use that approach either. Can you please advise? Thanks willbour@me.com

**Comment by tschuelia** [comment]
Hi Bill, thanks for raising that issue and solving it yourself (the fix was mentioned in an email chain for everyone reading this and wondering where the fix is :-)) 
I added your solution to the wiki and mentioned you, I hope that is okay :-)
